# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: r

env:
  - warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

sudo: required
